name = "dc-agent-ha-baby-20260318"
main = "index.js"
compatibility_date = "2026-03-18"


[vars]
DISCORD_PUBLIC_KEY = "53d7b353c70d556ea3539527e8a2efbebd31d0f971fa12f48cfb0562717fcfcd"
IS_DEV = "false" # 部署時設為 false，本地測試時改成 true

[[kv_namespaces]]
binding = "LIMITS"
id = "632cc5cfaa874dcea23244fd53c267b9"

[[kv_namespaces]]
binding = "SETTINGS"
id = "632cc5cfaa874dcea23244fd53c267b9"

[site]
bucket = "./public"
